spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/polyglot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}

  jpa:
    database: postgresql
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: true
server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: false
  port: 8080